name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'app/**'
      - '.github/workflows/ci-cd.yml'
      - 'Dockerfile'
  pull_request:
    branches: [ main ]
    paths:
      - 'app/**'
      - '.github/workflows/ci-cd.yml'
      - 'Dockerfile'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
          pip install -r tests/requirements-test.txt
          
      - name: Run tests
        run: pytest

  security-scan:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install security tools
        run: |
            python -m pip install --upgrade pip
            pip install bandit safety
            
      - name: Run static code analysis
        run: bandit -r app/ --skip B104
          
      - name: Check dependencies for vulnerabilities
        run: safety check -r app/requirements.txt

  build-and-push:
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/simpletimeservice:latest,${{ secrets.DOCKERHUB_USERNAME }}/simpletimeservice:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/simpletimeservice:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/simpletimeservice:buildcache,mode=max

  terraform-deploy:
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Create Terraform Backend Infrastructure
        run: |
            # Check if the bucket already exists
            if aws s3api head-bucket --bucket simpletimeservice-terraform-state 2>/dev/null; then
              echo "Bucket already exists, skipping creation"
            else
              # For us-east-1, don't use LocationConstraint
              if [ "${{ secrets.AWS_REGION }}" = "us-east-1" ]; then
                aws s3api create-bucket \
                  --bucket simpletimeservice-terraform-state \
                  --region us-east-1
              else
                # For other regions, use the region as LocationConstraint
                aws s3api create-bucket \
                  --bucket simpletimeservice-terraform-state \
                  --region ${{ secrets.AWS_REGION }} \
                  --create-bucket-configuration LocationConstraint=${{ secrets.AWS_REGION }}
              fi
            fi
            
            # Enable versioning
            aws s3api put-bucket-versioning \
              --bucket simpletimeservice-terraform-state \
              --versioning-configuration Status=Enabled
            
            # Enable encryption
            aws s3api put-bucket-encryption \
              --bucket simpletimeservice-terraform-state \
              --server-side-encryption-configuration '{
                "Rules": [
                  {
                    "ApplyServerSideEncryptionByDefault": {
                      "SSEAlgorithm": "AES256"
                    }
                  }
                ]
              }'
            
            # Check if the DynamoDB table already exists
            if aws dynamodb describe-table --table-name simpletimeservice-terraform-lock --region ${{ secrets.AWS_REGION }} 2>/dev/null; then
              echo "DynamoDB table already exists, skipping creation"
            else
              # Create DynamoDB table
              aws dynamodb create-table \
                --table-name simpletimeservice-terraform-lock \
                --attribute-definitions AttributeName=LockID,AttributeType=S \
                --key-schema AttributeName=LockID,KeyType=HASH \
                --billing-mode PAY_PER_REQUEST \
                --region ${{ secrets.AWS_REGION }}
            fi
        continue-on-error: true
            
      - name: Terraform Init
        run: |
          cd terraform
          terraform init
          
      - name: Terraform Plan
        run: |
          cd terraform
          terraform plan -out=tfplan
          
      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve tfplan
