name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install -r tests/requirements-test.txt
        
    - name: Run tests
      run: pytest
      
    - name: Build Docker image
      run: docker build -t simpletimeservice:${{ github.sha }} .
      
    - name: Test Docker image
      run: |
        docker run -d -p 8000:8000 --name test-container simpletimeservice:${{ github.sha }}
        sleep 5
        curl -s http://localhost:8000/ | grep -q "timestamp"
        docker stop test-container
