name: Greetings

on: [watch]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        watch-message: |
          Thank you for taking the time to review this project. This repository contains my submission for the [Assessment Name/Title].
          Feel free to explore the code, review the documentation, and let me know if you have any questions or feedback.
          
          I hope this meets the expectations of the assessment. Happy reviewing! 😊
