name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install -r tests/requirements-test.txt
        pip install bandit safety
    
    - name: Run Bandit (Static Code Analysis)
      run: |
        bandit -r app/ -f txt -o bandit-results.txt
      continue-on-error: true
      
    - name: Display Bandit results
      run: cat bandit-results.txt
        
    - name: Run Safety (Dependency Check)
      run: safety check -r app/requirements.txt --key ${{ secrets.SAFETY_API_KEY }} 
      continue-on-error: true
      
    
