name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit safety
    
    - name: Run Bandit (Static Code Analysis)
      run: |
        bandit -r app/ -f txt -o bandit-results.txt
      continue-on-error: true
      
    - name: Display Bandit results
      run: cat bandit-results.txt
        
    - name: Run Safety (Dependency Check)
      run: safety check -r requirements.txt --json > safety-results.json
      continue-on-error: true
      
    - name: Display Safety results
      run: cat safety-results.json
      
    - name: Check for critical vulnerabilities
      run: |
        if grep -q '"severity": "critical"' safety-results.json; then
          echo "Critical vulnerabilities found!"
          exit 1
        fi
